### PR TITLE
Auto load movies on scroll

### PR DESCRIPTION
**Pull request by julieg18**
* updated `Home.js` to have a window event listener that listens for the scroll event and loads more movies on scroll
* updated needed `useState` variables in `Home.js` and `useHomeFetch.js` to have refs so they could be usable in event listener functions
* deleted "Load More" component

### CODE REVIEW

**Comment by tarunyadav1** [comment]
Add a Loading animation at bottom of the page during api call

**Comment by julieg18** [comment]
> Add a Loading animation at bottom of the page during api call

That's strange, I thought there was one on [line 127 of Home.js](https://github.com/tarunyadav1/Movie-Library-App-using-Reactjs-and-The-MovieDB-API/pull/10/files#diff-0a88c1029acca98fe79261c7260c9bbdR128)

**Comment by tarunyadav1** [comment]
Leave, I will create another issue.
Thank you for your contribution.

**Comment by julieg18** [comment]
You're welcome! Glad I could help! Could you place a "hacktoberfest-accepted" label to the PR? I'm working towards completing the [Hacktoberfest](https://hacktoberfest.digitalocean.com/details) challenge, and the pull request doesn't count until the label is placed on it.

**Comment by julieg18** [comment]
Thanks!

**Pull request merged**
